service: visor-account-lmb-api
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1

functions:
  functionName:
  AccountLmb:
    handler: index.handler
    events:
      - httpApi: "*"

plugins:
  - serverless-offline

custom:
  serverless-offline:
    host: 0.0.0.0
