name: Build

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string

run-name: "Build Staging"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: "Install Dependencies"
        run: npm install

      - name: "Unit tests"
        run: npm run unit:test

