name: Release

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
  
    secrets:
      AWS_COGNITO_REGION: 
        required: true    
      AWS_COGNITO_CLIENT_ID: 
        required: true
      AWS_ACCESS_KEY_ID: 
        required: true
      AWS_SECRET_ACCESS_KEY: 
        required: true

run-name: "Release Staging"
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}

      - name: "Install Dependencies"
        run: npm install

      - name: serverless deploy
        uses: serverless/github-action@v3.1
        with:
          args: deploy
        env:
         AWS_COGNITO_REGION: ${{ secrets.AWS_COGNITO_REGION }} 
         AWS_COGNITO_CLIENT_ID: ${{ secrets.AWS_COGNITO_CLIENT_ID }} 
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}