name: Release

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
  
    secrets:
      AWS_COGNITO_REGION: 
        required: true    
      AWS_COGNITO_CLIENT_ID: 
        required: true
      AWS_ACCESS_KEY_ID: 
        required: true
      AWS_SECRET_ACCESS_KEY: 
        required: true

run-name: "Release Staging"
jobs:
  deploy:
    runs-on: ubuntu-latest
    container: node:18-alpine3.17

    steps:
      - uses: actions/checkout@v3
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: .
          node-version: ${{ inputs.node-version }}
          key: ${{ env.cache-name }}${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ env.cache-name }}

      - name: "Install Dependencies"
        if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        run: npm install

      - name: serverless deploy
        uses: serverless/github-action@v3.1
        with:
          args: deploy
        env:
         AWS_COGNITO_REGION: ${{ secrets.AWS_COGNITO_REGION }} 
         AWS_COGNITO_CLIENT_ID: ${{ secrets.AWS_COGNITO_CLIENT_ID }} 
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}