name: Build

on:
  workflow_call:
    secrets:
      AWS_COGNITO_REGION: 
        required: true    
      AWS_COGNITO_CLIENT_ID: 
        required: true
      AWS_ACCESS_KEY_ID: 
        required: true
      AWS_SECRET_ACCESS_KEY: 
        required: true

run-name: "Release Staging"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: serverless deploy
        uses: serverless/github-action@v3.1
        with:
          args: deploy
        env:
         AWS_COGNITO_REGION: ${{ env.AWS_COGNITO_REGION }} 
         AWS_COGNITO_CLIENT_ID: ${{ secrets.AWS_COGNITO_CLIENT_ID }} 
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}